apiVersion: v1
kind: Service
metadata:
  name: sample-springboot-service
  namespace: default
spec:
  selector:
    app: sample-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
