name: Docker Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package

      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/$REPO_OWNER/sample-springboot-app:latest .
          docker tag ghcr.io/$REPO_OWNER/sample-springboot-app:latest ghcr.io/$REPO_OWNER/sample-springboot-app:${{ github.run_number }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/$REPO_OWNER/sample-springboot-app:latest
          docker push ghcr.io/$REPO_OWNER/sample-springboot-app:${{ github.run_number }}
